/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
public class Alimentos extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    int xMouse,yMouse;
    String FTabla = "productos";
    String FClave = "clave_producto";
    String FNombre = "nombre";
    String FPrecio = "precio";
    String FInventario = "inventario";
    public Alimentos() {
        initComponents();
        Conectar();
        TablaSet();
        loadTabla();
        Jpanelinforme.setVisible(false);
        jpanelOPbarra.setVisible(false);
        SetImageLabel(imgblanclo,"src/imagenes/cosa.png");
        SetImageLabel(imgblanclo1,"src/imagenes/cosa.png");
        SetImageLabel(imgblanclo2,"src/imagenes/cosa.png");
        SetImageLabel(ImgNUM,"src/imagenes/borde.png");
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alimentos = new javax.swing.JPanel();
        Jpanelinforme = new javax.swing.JPanel();
        TxtMayorprecio = new javax.swing.JLabel();
        Imgborde = new javax.swing.JLabel();
        TxtMaximo = new javax.swing.JLabel();
        TxtMenorprecio = new javax.swing.JLabel();
        Imgborde1 = new javax.swing.JLabel();
        TxtMinimo = new javax.swing.JLabel();
        TxtPromedio = new javax.swing.JLabel();
        Imgborde2 = new javax.swing.JLabel();
        TxtTPromedio = new javax.swing.JLabel();
        TxtValortotal = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JLabel();
        Imgborde3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ImgEstees = new javax.swing.JLabel();
        jPanelbarrasuperior = new javax.swing.JPanel();
        jPanelsalida = new javax.swing.JPanel();
        TxtXsalida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TxtOP = new javax.swing.JLabel();
        jpanelOPbarra = new javax.swing.JPanel();
        jPanelTabla1 = new javax.swing.JPanel();
        TxtTablaset1 = new javax.swing.JLabel();
        jPanelSQLSet = new javax.swing.JPanel();
        TxtSQLSet = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        TxtSalir = new javax.swing.JLabel();
        jPanelINVENTARIO = new javax.swing.JPanel();
        TxtINVENTARO = new javax.swing.JLabel();
        FieldINVENTARIO = new javax.swing.JTextField();
        TxtNOMBRE2 = new javax.swing.JLabel();
        imgblanclo2 = new javax.swing.JLabel();
        FieldPRECIO = new javax.swing.JTextField();
        TxtNOMBRE1 = new javax.swing.JLabel();
        imgblanclo1 = new javax.swing.JLabel();
        TxtNOMBRE = new javax.swing.JLabel();
        TxtNUM = new javax.swing.JLabel();
        ImgNUM = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        imgblanclo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanelINFORME = new javax.swing.JPanel();
        TxtINFORME = new javax.swing.JLabel();
        jPanelAGREGAR = new javax.swing.JPanel();
        TxtAGREGAR = new javax.swing.JLabel();
        jPanelACTUALIZAR = new javax.swing.JPanel();
        TxtACTUALIZAR = new javax.swing.JLabel();
        jPanelELIMINAR = new javax.swing.JPanel();
        TxtELIMINAR = new javax.swing.JLabel();
        jPanelLIMPIAR = new javax.swing.JPanel();
        TxtLIMPIAR = new javax.swing.JLabel();
        imgWifu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Alimentos.setBackground(new java.awt.Color(255, 255, 255));
        Alimentos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanelinforme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        Jpanelinforme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtMayorprecio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtMayorprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMayorprecio.setText("EL PRODUCTO DE MAYOR PRECIO:");
        Jpanelinforme.add(TxtMayorprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 32));

        Imgborde.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Imgborde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jpanelinforme.add(Imgborde, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 168, 32));

        TxtMaximo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtMaximo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMaximo.setText("Maximo");
        Jpanelinforme.add(TxtMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 168, 32));

        TxtMenorprecio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtMenorprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMenorprecio.setText("EL PRODUCTO DE MENOR PRECIO:");
        Jpanelinforme.add(TxtMenorprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 32));

        Imgborde1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Imgborde1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jpanelinforme.add(Imgborde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 168, 32));

        TxtMinimo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtMinimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMinimo.setText("Minimo");
        Jpanelinforme.add(TxtMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 168, 32));

        TxtPromedio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPromedio.setText("EL PROMEDIO DE PRECIOS ES:");
        Jpanelinforme.add(TxtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 32));

        Imgborde2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Imgborde2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jpanelinforme.add(Imgborde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 168, 32));

        TxtTPromedio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtTPromedio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTPromedio.setText("Promedio");
        Jpanelinforme.add(TxtTPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 168, 32));

        TxtValortotal.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtValortotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtValortotal.setText("EL TOTAL DEL INVENTARIO ES:");
        Jpanelinforme.add(TxtValortotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 190, 32));

        TxtTotal.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTotal.setText("Inventario");
        Jpanelinforme.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 168, 32));

        Imgborde3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Imgborde3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jpanelinforme.add(Imgborde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 168, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("tu informe.");
        Jpanelinforme.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 150, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Este es");
        Jpanelinforme.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 150, 30));
        Jpanelinforme.add(ImgEstees, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, 190));

        Alimentos.add(Jpanelinforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 510, 390));

        jPanelbarrasuperior.setBackground(new java.awt.Color(204, 204, 204));
        jPanelbarrasuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelbarrasuperiorMouseDragged(evt);
            }
        });
        jPanelbarrasuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelbarrasuperiorMousePressed(evt);
            }
        });

        jPanelsalida.setBackground(new java.awt.Color(204, 204, 204));

        TxtXsalida.setBackground(new java.awt.Color(153, 153, 153));
        TxtXsalida.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtXsalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtXsalida.setText("x");
        TxtXsalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtXsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelsalidaLayout = new javax.swing.GroupLayout(jPanelsalida);
        jPanelsalida.setLayout(jPanelsalidaLayout);
        jPanelsalidaLayout.setHorizontalGroup(
            jPanelsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsalidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtXsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelsalidaLayout.setVerticalGroup(
            jPanelsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtXsalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        TxtOP.setBackground(new java.awt.Color(204, 204, 204));
        TxtOP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtOP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtOP.setText("OP");
        TxtOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtOPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtOPMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtOPMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtOP, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtOP, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelbarrasuperiorLayout = new javax.swing.GroupLayout(jPanelbarrasuperior);
        jPanelbarrasuperior.setLayout(jPanelbarrasuperiorLayout);
        jPanelbarrasuperiorLayout.setHorizontalGroup(
            jPanelbarrasuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbarrasuperiorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 894, Short.MAX_VALUE)
                .addComponent(jPanelsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelbarrasuperiorLayout.setVerticalGroup(
            jPanelbarrasuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbarrasuperiorLayout.createSequentialGroup()
                .addGroup(jPanelbarrasuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Alimentos.add(jPanelbarrasuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        jpanelOPbarra.setBackground(new java.awt.Color(190, 190, 190));
        jpanelOPbarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpanelOPbarraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanelOPbarraMouseExited(evt);
            }
        });
        jpanelOPbarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTabla1.setBackground(new java.awt.Color(190, 190, 190));

        TxtTablaset1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtTablaset1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtTablaset1.setText("TablaSet");
        TxtTablaset1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTablaset1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtTablaset1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtTablaset1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelTabla1Layout = new javax.swing.GroupLayout(jPanelTabla1);
        jPanelTabla1.setLayout(jPanelTabla1Layout);
        jPanelTabla1Layout.setHorizontalGroup(
            jPanelTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabla1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TxtTablaset1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelTabla1Layout.setVerticalGroup(
            jPanelTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelTabla1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTabla1Layout.createSequentialGroup()
                    .addComponent(TxtTablaset1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanelOPbarra.add(jPanelTabla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        jPanelSQLSet.setBackground(new java.awt.Color(190, 190, 190));

        TxtSQLSet.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtSQLSet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtSQLSet.setText("SQLSet");
        TxtSQLSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtSQLSetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtSQLSetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtSQLSetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSQLSetLayout = new javax.swing.GroupLayout(jPanelSQLSet);
        jPanelSQLSet.setLayout(jPanelSQLSetLayout);
        jPanelSQLSetLayout.setHorizontalGroup(
            jPanelSQLSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelSQLSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSQLSetLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TxtSQLSet, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSQLSetLayout.setVerticalGroup(
            jPanelSQLSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
            .addGroup(jPanelSQLSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSQLSetLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TxtSQLSet, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanelOPbarra.add(jPanelSQLSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 20));

        jPanelSalir.setBackground(new java.awt.Color(190, 190, 190));

        TxtSalir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TxtSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtSalir.setText("Salir");
        TxtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TxtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelSalirLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TxtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpanelOPbarra.add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 80, 20));

        Alimentos.add(jpanelOPbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 60));

        jPanelINVENTARIO.setBackground(new java.awt.Color(255, 255, 255));
        jPanelINVENTARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TxtINVENTARO.setBackground(new java.awt.Color(255, 255, 255));
        TxtINVENTARO.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxtINVENTARO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtINVENTARO.setText("INVENTARIO CAFETERIA ");

        javax.swing.GroupLayout jPanelINVENTARIOLayout = new javax.swing.GroupLayout(jPanelINVENTARIO);
        jPanelINVENTARIO.setLayout(jPanelINVENTARIOLayout);
        jPanelINVENTARIOLayout.setHorizontalGroup(
            jPanelINVENTARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINVENTARIOLayout.createSequentialGroup()
                .addComponent(TxtINVENTARO, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelINVENTARIOLayout.setVerticalGroup(
            jPanelINVENTARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtINVENTARO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelINVENTARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 330, 50));

        FieldINVENTARIO.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldINVENTARIO.setForeground(new java.awt.Color(204, 204, 204));
        FieldINVENTARIO.setText("Inventario");
        FieldINVENTARIO.setBorder(null);
        FieldINVENTARIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldINVENTARIOMousePressed(evt);
            }
        });
        FieldINVENTARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldINVENTARIOActionPerformed(evt);
            }
        });
        Alimentos.add(FieldINVENTARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 130, 30));

        TxtNOMBRE2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtNOMBRE2.setText("INVENTARIO:");
        Alimentos.add(TxtNOMBRE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 325, 140, 60));
        Alimentos.add(imgblanclo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 240, 30));

        FieldPRECIO.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldPRECIO.setForeground(new java.awt.Color(204, 204, 204));
        FieldPRECIO.setText("Precio");
        FieldPRECIO.setBorder(null);
        FieldPRECIO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldPRECIOMousePressed(evt);
            }
        });
        FieldPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPRECIOActionPerformed(evt);
            }
        });
        Alimentos.add(FieldPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 130, 30));

        TxtNOMBRE1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtNOMBRE1.setText("PRECIO:");
        Alimentos.add(TxtNOMBRE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 243, 140, 60));
        Alimentos.add(imgblanclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 210, 30));

        TxtNOMBRE.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtNOMBRE.setText("NOMBRE/CP:");
        Alimentos.add(TxtNOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 165, 140, 60));

        TxtNUM.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtNUM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtNUM.setText("NUM");
        Alimentos.add(TxtNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));

        ImgNUM.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Alimentos.add(ImgNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 90, 30));

        FieldNombre.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldNombre.setForeground(new java.awt.Color(204, 204, 204));
        FieldNombre.setText("Nombre");
        FieldNombre.setBorder(null);
        FieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldNombreMousePressed(evt);
            }
        });
        Alimentos.add(FieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 30));
        Alimentos.add(imgblanclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 30));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "clave", "nombre", "precio", "inventario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductos);

        Alimentos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 510, 400));

        jPanelINFORME.setBackground(new java.awt.Color(64, 143, 206));

        TxtINFORME.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtINFORME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtINFORME.setText("INFORME");
        TxtINFORME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtINFORME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtINFORMEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtINFORMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtINFORMEMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelINFORMELayout = new javax.swing.GroupLayout(jPanelINFORME);
        jPanelINFORME.setLayout(jPanelINFORMELayout);
        jPanelINFORMELayout.setHorizontalGroup(
            jPanelINFORMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtINFORME, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanelINFORMELayout.setVerticalGroup(
            jPanelINFORMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtINFORME, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelINFORME, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 130, 30));

        jPanelAGREGAR.setBackground(new java.awt.Color(207, 207, 207));

        TxtAGREGAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtAGREGAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtAGREGAR.setText("AGREGAR");
        TxtAGREGAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtAGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtAGREGARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtAGREGARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtAGREGARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelAGREGARLayout = new javax.swing.GroupLayout(jPanelAGREGAR);
        jPanelAGREGAR.setLayout(jPanelAGREGARLayout);
        jPanelAGREGARLayout.setHorizontalGroup(
            jPanelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtAGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelAGREGARLayout.setVerticalGroup(
            jPanelAGREGARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtAGREGAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelAGREGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 90, 30));

        jPanelACTUALIZAR.setBackground(new java.awt.Color(207, 207, 207));

        TxtACTUALIZAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtACTUALIZAR.setText("ACTUALIZAR");
        TxtACTUALIZAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtACTUALIZARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtACTUALIZARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtACTUALIZARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelACTUALIZARLayout = new javax.swing.GroupLayout(jPanelACTUALIZAR);
        jPanelACTUALIZAR.setLayout(jPanelACTUALIZARLayout);
        jPanelACTUALIZARLayout.setHorizontalGroup(
            jPanelACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelACTUALIZARLayout.setVerticalGroup(
            jPanelACTUALIZARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jPanelELIMINAR.setBackground(new java.awt.Color(207, 207, 207));

        TxtELIMINAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtELIMINAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtELIMINAR.setText("ELIMINAR");
        TxtELIMINAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtELIMINAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtELIMINARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtELIMINARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtELIMINARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelELIMINARLayout = new javax.swing.GroupLayout(jPanelELIMINAR);
        jPanelELIMINAR.setLayout(jPanelELIMINARLayout);
        jPanelELIMINARLayout.setHorizontalGroup(
            jPanelELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelELIMINARLayout.setVerticalGroup(
            jPanelELIMINARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        jPanelLIMPIAR.setBackground(new java.awt.Color(207, 207, 207));

        TxtLIMPIAR.setBackground(new java.awt.Color(180, 180, 180));
        TxtLIMPIAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtLIMPIAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtLIMPIAR.setText("LIMPIAR");
        TxtLIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtLIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelLIMPIARLayout = new javax.swing.GroupLayout(jPanelLIMPIAR);
        jPanelLIMPIAR.setLayout(jPanelLIMPIARLayout);
        jPanelLIMPIARLayout.setHorizontalGroup(
            jPanelLIMPIARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelLIMPIARLayout.setVerticalGroup(
            jPanelLIMPIARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Alimentos.add(jPanelLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        imgWifu.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imgWifu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/25.png"))); // NOI18N
        imgWifu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imgWifu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        imgWifu.setIconTextGap(10);
        Alimentos.add(imgWifu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alimentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtXsalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TxtXsalidaMouseClicked

    private void TxtXsalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseEntered
        jPanelsalida.setBackground(Color.red);
        TxtXsalida.setForeground(Color.white);
    }//GEN-LAST:event_TxtXsalidaMouseEntered

    private void TxtXsalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseExited
        jPanelsalida.setBackground(new Color(204, 204, 204));
        TxtXsalida.setForeground(Color.black);
    }//GEN-LAST:event_TxtXsalidaMouseExited

    private void jPanelbarrasuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarrasuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanelbarrasuperiorMouseDragged

    private void jPanelbarrasuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarrasuperiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanelbarrasuperiorMousePressed

    private void FieldINVENTARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldINVENTARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldINVENTARIOActionPerformed

    private void FieldPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPRECIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPRECIOActionPerformed

    private void FieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldNombreMousePressed
        if(FieldNombre.getText().equals("Nombre")){
            FieldNombre.setText("");
            FieldNombre.setForeground(Color.black);
        }
        if(FieldPRECIO.getText().isEmpty()){
            FieldPRECIO.setText("Precio");
            FieldPRECIO.setForeground(Color.gray);
        }
        if(FieldINVENTARIO.getText().isEmpty()){
            FieldINVENTARIO.setText("Inventario");
            FieldINVENTARIO.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldNombreMousePressed

    private void FieldPRECIOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldPRECIOMousePressed
        FieldPRECIO.setFocusable(true);
        if(FieldPRECIO.getText().equals("Precio")){
            FieldPRECIO.setText("");
            FieldPRECIO.setForeground(Color.black);
        }
        if(FieldNombre.getText().isEmpty()){
            FieldNombre.setText("Nombre");
            FieldNombre.setForeground(Color.gray);
        }
        if(FieldINVENTARIO.getText().isEmpty()){
            FieldINVENTARIO.setText("Inventario");
            FieldINVENTARIO.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldPRECIOMousePressed

    private void FieldINVENTARIOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldINVENTARIOMousePressed
        if(FieldINVENTARIO.getText().equals("Inventario")){
            FieldINVENTARIO.setText("");
            FieldINVENTARIO.setForeground(Color.black);
        }
        if(FieldNombre.getText().isEmpty()){
            FieldNombre.setText("Nombre");
            FieldNombre.setForeground(Color.gray);
        }
        if(FieldPRECIO.getText().isEmpty()){
            FieldPRECIO.setText("Precio");
            FieldPRECIO.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldINVENTARIOMousePressed

    private void TxtINFORMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtINFORMEMouseEntered
        if(Jpanelinforme.isVisible() == false){
            jPanelINFORME.setBackground(new Color(64,176,218));
        }else{
            jPanelINFORME.setBackground(new Color(255,255,0));
        }
    }//GEN-LAST:event_TxtINFORMEMouseEntered

    private void TxtINFORMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtINFORMEMouseExited
        if(Jpanelinforme.isVisible() == false){
            jPanelINFORME.setBackground(new Color(64,143,206));
        }else{
            jPanelINFORME.setBackground(new Color(255,204,0));
        }
    }//GEN-LAST:event_TxtINFORMEMouseExited

    private void TxtAGREGARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAGREGARMouseEntered
        jPanelAGREGAR.setBackground(new Color(170,194,215));
    }//GEN-LAST:event_TxtAGREGARMouseEntered

    private void TxtACTUALIZARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtACTUALIZARMouseEntered
        jPanelACTUALIZAR.setBackground(new Color(170,194,215));
    }//GEN-LAST:event_TxtACTUALIZARMouseEntered

    private void TxtELIMINARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtELIMINARMouseEntered
        jPanelELIMINAR.setBackground(new Color(170,194,215));
    }//GEN-LAST:event_TxtELIMINARMouseEntered

    private void TxtLIMPIARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseEntered
        jPanelLIMPIAR.setBackground(new Color(170,194,215));
    }//GEN-LAST:event_TxtLIMPIARMouseEntered

    private void TxtAGREGARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAGREGARMouseExited
        jPanelAGREGAR.setBackground(new Color(207,207,207));
    }//GEN-LAST:event_TxtAGREGARMouseExited

    private void TxtACTUALIZARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtACTUALIZARMouseExited
        jPanelACTUALIZAR.setBackground(new Color(207,207,207));
    }//GEN-LAST:event_TxtACTUALIZARMouseExited

    private void TxtELIMINARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtELIMINARMouseExited
        jPanelELIMINAR.setBackground(new Color(207,207,207));
    }//GEN-LAST:event_TxtELIMINARMouseExited

    private void TxtLIMPIARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseExited
        jPanelLIMPIAR.setBackground(new Color(207,207,207));
    }//GEN-LAST:event_TxtLIMPIARMouseExited

    private void TxtACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtACTUALIZARMouseClicked
        Conectar();
        try {
            int id = Integer.parseInt(TxtNUM.getText());
            
            ps = con.prepareStatement("UPDATE "+FTabla+" SET "+FNombre+"=?,"+FPrecio+"=?,"+FInventario+"=? WHERE "+FClave+"=?");
            ps.setString(1, FieldNombre.getText());
            ps.setDouble(2, Double.parseDouble(FieldPRECIO.getText()));
            ps.setInt(3, Integer.parseInt(FieldINVENTARIO.getText()));
            ps.setInt(4,Integer.parseInt(TxtNUM.getText()));
            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        }
        limpiar();
    }//GEN-LAST:event_TxtACTUALIZARMouseClicked

    private void TxtINFORMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtINFORMEMouseClicked
        if(TxtINFORME.getText().equals("INFORME")){
            TxtINFORME.setText("CERRAR");
            jTableProductos.setVisible(false);
            jScrollPane1.setVisible(false);
            Jpanelinforme.setVisible(true);
            jPanelINFORME.setBackground(new Color(255,255,0));
            SetImageLabel(ImgEstees,"src/imagenes/pr4.png");
            SetImageLabel(Imgborde,"src/imagenes/borde.png");
            SetImageLabel(Imgborde1,"src/imagenes/borde.png");
            SetImageLabel(Imgborde2,"src/imagenes/borde.png");
            SetImageLabel(Imgborde3,"src/imagenes/borde.png");
            try{
                ps = con.prepareStatement("SELECT "+FNombre+" AS Mayor FROM "+FTabla+" WHERE "+FPrecio+" = (SELECT MAX("+FPrecio+") FROM "+FTabla+")");
                rs = ps.executeQuery();

                while(rs.next()){
                    TxtMaximo.setText(rs.getString("Mayor"));

                }
                ps = con.prepareStatement("SELECT "+FNombre+" AS Menor FROM "+FTabla+" WHERE "+FPrecio+" = (SELECT MIN("+FPrecio+") FROM "+FTabla+")");
                rs = ps.executeQuery();

                while(rs.next()){
                    TxtMinimo.setText(rs.getString("Menor"));
                }
                ps = con.prepareStatement("SELECT AVG("+FPrecio+") AS promedio,SUM("+FPrecio+"*"+FInventario+") AS total_inventario FROM "+FTabla+"");
                rs = ps.executeQuery();

                while(rs.next()){
                    TxtTPromedio.setText(rs.getString("promedio"));
                    TxtTotal.setText(rs.getString("total_inventario"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Tabla solicitada no existente, dirijete a OP/TablaSet."); 
            }              
        }else if(TxtINFORME.getText().equals("CERRAR")){
            TxtINFORME.setText("INFORME");
            Jpanelinforme.setVisible(false);
            jTableProductos.setVisible(true);
            jScrollPane1.setVisible(true);
            jPanelINFORME.setBackground(new Color(64,176,218));
            
        }
    }//GEN-LAST:event_TxtINFORMEMouseClicked

    private void TxtAGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAGREGARMouseClicked
        Conectar();
        try {
            ps = con.prepareStatement("INSERT INTO "+FTabla+" ("+FNombre+","+FPrecio+","+FInventario+") VALUES(?,?,?)");
            ps.setString(1, FieldNombre.getText());
            ps.setDouble(2, Double.parseDouble(FieldPRECIO.getText()));
            ps.setInt(3, Integer.parseInt(FieldINVENTARIO.getText()));
            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        }
        limpiar();
    }//GEN-LAST:event_TxtAGREGARMouseClicked

    private void TxtLIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseClicked
        limpiar();
    }//GEN-LAST:event_TxtLIMPIARMouseClicked

    private void jTableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductosMouseClicked
        try{
            int fila = jTableProductos.getSelectedRow();
            int id = Integer.parseInt(jTableProductos.getValueAt(fila, 0).toString());
            ps = con.prepareStatement("SELECT * FROM "+FTabla+" WHERE "+FClave+"=?");
            ps.setInt(1,id);
            rs = ps.executeQuery();
            
            while(rs.next()){
                TxtNUM.setText(String.valueOf(id));
                FieldNombre.setText(rs.getString(FNombre));
                FieldNombre.setForeground(Color.black);
                FieldPRECIO.setText(rs.getString(FPrecio));
                FieldPRECIO.setForeground(Color.black);
                FieldINVENTARIO.setText(rs.getString(FInventario));
                FieldINVENTARIO.setForeground(Color.black);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, precions limpiar e intenta de nuevo"); 
        }
    }//GEN-LAST:event_jTableProductosMouseClicked

    private void TxtELIMINARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtELIMINARMouseClicked
        Conectar();
        try {
            int id = Integer.parseInt(TxtNUM.getText());
                    
            ps = con.prepareStatement("DELETE FROM "+FTabla+" WHERE "+FClave+"=?");
            ps.setInt(1,Integer.parseInt(TxtNUM.getText()));
            ps.executeUpdate();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Parece que ingresaste una entreda erronea, revisa e intenta de nuevo"); 
        }
        limpiar();
    }//GEN-LAST:event_TxtELIMINARMouseClicked

    private void TxtOPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtOPMouseEntered
        jPanel1.setBackground(new Color(153,153,153));

    }//GEN-LAST:event_TxtOPMouseEntered

    private void TxtOPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtOPMouseExited
        jPanel1.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_TxtOPMouseExited

    private void jpanelOPbarraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOPbarraMouseEntered

    }//GEN-LAST:event_jpanelOPbarraMouseEntered

    private void jpanelOPbarraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelOPbarraMouseExited

    }//GEN-LAST:event_jpanelOPbarraMouseExited

    private void TxtOPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtOPMousePressed
        if(jpanelOPbarra.isVisible()==false){
            jpanelOPbarra.setVisible(true);
        }else if (jpanelOPbarra.isVisible()==true){
            jpanelOPbarra.setVisible(false);
        }
    }//GEN-LAST:event_TxtOPMousePressed

    private void TxtSQLSetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSQLSetMouseEntered
        jPanelSQLSet.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_TxtSQLSetMouseEntered

    private void TxtSQLSetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSQLSetMouseExited
        jPanelSQLSet.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_TxtSQLSetMouseExited

    private void TxtTablaset1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTablaset1MouseEntered
        jPanelTabla1.setBackground(new Color(153,153,153));  
    }//GEN-LAST:event_TxtTablaset1MouseEntered

    private void TxtTablaset1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTablaset1MouseExited
        jPanelTabla1.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_TxtTablaset1MouseExited

    private void TxtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSalirMouseEntered
        jPanelSalir.setBackground(new Color(153,153,153));  
    }//GEN-LAST:event_TxtSalirMouseEntered

    private void TxtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSalirMouseExited
        jPanelSalir.setBackground(new Color(190,190,190));
    }//GEN-LAST:event_TxtSalirMouseExited

    private void TxtSQLSetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSQLSetMouseClicked
        Connexion Co = new Connexion();
        Co.setVisible(true);
        Co.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_TxtSQLSetMouseClicked

    private void TxtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TxtSalirMouseClicked

    private void TxtTablaset1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTablaset1MouseClicked
        TablaSet TS = new TablaSet();
        TS.setVisible(true);
        TS.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_TxtTablaset1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alimentos().setVisible(true);
            }
        });
    }
    private void SetImageLabel(JLabel labelName,String root){
        ImageIcon image=new ImageIcon(root);
        Icon icon=new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(),labelName.getHeight(),Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public void Conectar(){
        try{
        con = DriverManager.getConnection("jdbc:mysql://"+Connexion.HOSTNAME+":"+Connexion.PORT+"/"+Connexion.DATABASE+"?useSSL=false"
                ,Connexion.USERNAME,Connexion.PASSWORD);
        } catch(SQLException e){
        //JOptionPane.showMessageDialog(null, e.toString());
    }
    }
    private void limpiar(){
        FieldINVENTARIO.setText("Inventario");
        FieldINVENTARIO.setForeground(Color.gray);
        FieldPRECIO.setText("Precio");
        FieldPRECIO.setForeground(Color.gray);
        FieldNombre.setText("Nombre");
        FieldNombre.setForeground(Color.gray);
        TxtNUM.setText("NUM");
        loadTabla();
    }
    private void loadTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableProductos.getModel();
        modeloTabla.setRowCount(0);
        
        try {
            ps = con.prepareStatement("SELECT * FROM "+FTabla+"");
            rs = ps.executeQuery();
            Object[] cliente = new Object[4];
            while(rs.next()){
                cliente [0] = rs.getInt(FClave);
                cliente [1] = rs.getString(FNombre);
                cliente [2] = rs.getDouble(FPrecio);
                cliente [3] = rs.getInt(FInventario);
                
                modeloTabla.addRow(cliente);
            }
            jTableProductos.setModel(modeloTabla);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Tabla solicitada no existente, dirijete a OP/TablaSet."); 
        }
    }
    public void TablaSet(){
        try{
            if(TablaSet.MTable==true){
                FTabla = TablaSet.FTabla;
                FClave = TablaSet.FClave;
                FNombre = TablaSet.FNombre;
                FPrecio = TablaSet.FPrecio;
                FInventario = TablaSet.FInventario;
            }
        }catch(NullPointerException e){
            
        }
        }

    /*
    /*
    public void tablaSet(String DTabla){
        Object[] cosas = new Object[1];
        String f = "";
        int i=0;
        try {
            ps = con.prepareStatement("DESCRIBE "+DTabla+"");
            rs = ps.executeQuery();
            while(rs.next()){
                cosas[0] = rs.getString("Field");
                System.out.println(cosas[0].toString());
                if (i==0){
                    f= cosas[0].toString();
                }else{                  
                    f= f+" "+cosas[0].toString();
                }
                i++;
            }
            String[] x = f.split(" ");
            FTabla=DTabla;
            FClave=x[0];
            FNombre=x[1];
            FPrecio=x[2];
            FInventario=x[3];
        } catch (SQLException ex) {
            Logger.getLogger(Alimentos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alimentos;
    private javax.swing.JTextField FieldINVENTARIO;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldPRECIO;
    private javax.swing.JLabel ImgEstees;
    private javax.swing.JLabel ImgNUM;
    private javax.swing.JLabel Imgborde;
    private javax.swing.JLabel Imgborde1;
    private javax.swing.JLabel Imgborde2;
    private javax.swing.JLabel Imgborde3;
    private javax.swing.JPanel Jpanelinforme;
    private javax.swing.JLabel TxtACTUALIZAR;
    private javax.swing.JLabel TxtAGREGAR;
    private javax.swing.JLabel TxtELIMINAR;
    private javax.swing.JLabel TxtINFORME;
    private javax.swing.JLabel TxtINVENTARO;
    private javax.swing.JLabel TxtLIMPIAR;
    private javax.swing.JLabel TxtMaximo;
    private javax.swing.JLabel TxtMayorprecio;
    private javax.swing.JLabel TxtMenorprecio;
    private javax.swing.JLabel TxtMinimo;
    private javax.swing.JLabel TxtNOMBRE;
    private javax.swing.JLabel TxtNOMBRE1;
    private javax.swing.JLabel TxtNOMBRE2;
    private javax.swing.JLabel TxtNUM;
    private javax.swing.JLabel TxtOP;
    private javax.swing.JLabel TxtPromedio;
    private javax.swing.JLabel TxtSQLSet;
    private javax.swing.JLabel TxtSalir;
    private javax.swing.JLabel TxtTPromedio;
    private javax.swing.JLabel TxtTablaset1;
    private javax.swing.JLabel TxtTotal;
    private javax.swing.JLabel TxtValortotal;
    private javax.swing.JLabel TxtXsalida;
    private javax.swing.JLabel imgWifu;
    private javax.swing.JLabel imgblanclo;
    private javax.swing.JLabel imgblanclo1;
    private javax.swing.JLabel imgblanclo2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelACTUALIZAR;
    private javax.swing.JPanel jPanelAGREGAR;
    private javax.swing.JPanel jPanelELIMINAR;
    private javax.swing.JPanel jPanelINFORME;
    private javax.swing.JPanel jPanelINVENTARIO;
    private javax.swing.JPanel jPanelLIMPIAR;
    private javax.swing.JPanel jPanelSQLSet;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelTabla1;
    private javax.swing.JPanel jPanelbarrasuperior;
    private javax.swing.JPanel jPanelsalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JPanel jpanelOPbarra;
    // End of variables declaration//GEN-END:variables
}
