/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.sql.Connection;
import java.awt.Color;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author hogud
 */
public class Connexion extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    int xMouse,yMouse;
    static String HOSTNAME;
    static String PORT;
    static String DATABASE;
    static String USERNAME;
    static String PASSWORD;
    
    public Connexion() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel1.setVisible(false);
        jPanel4.setVisible(false);
        SetImageLabel(ImgWifu,"src/imagenes/Wifu2.png");
        SetImageLabel(ImgMinticl,"src/imagenes/logo-mision.png");
        SetImageLabel(imgborde1,"src/imagenes/borde.png");
        SetImageLabel(imgborde2,"src/imagenes/borde.png");
        SetImageLabel(imgborde3,"src/imagenes/borde.png");
        SetImageLabel(imgborde4,"src/imagenes/borde.png");
        SetImageLabel(imgborde5,"src/imagenes/borde.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txtuniversidad = new javax.swing.JPanel();
        jPanelbarrasuperior = new javax.swing.JPanel();
        jPanelsalida = new javax.swing.JPanel();
        TxtXsalida = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TxtSergio = new javax.swing.JLabel();
        TxtUniver = new javax.swing.JLabel();
        ImgWifu = new javax.swing.JLabel();
        ImgCity = new javax.swing.JLabel();
        TxtUniversidad = new javax.swing.JLabel();
        ImgMinticl = new javax.swing.JLabel();
        TxtINVENTARO = new javax.swing.JLabel();
        TxtSQLserver = new javax.swing.JLabel();
        TxtHostnamePort = new javax.swing.JLabel();
        FieldHostname = new javax.swing.JTextField();
        imgborde1 = new javax.swing.JLabel();
        FieldPort = new javax.swing.JTextField();
        imgborde2 = new javax.swing.JLabel();
        TxtDatabase = new javax.swing.JLabel();
        FieldDatabase = new javax.swing.JTextField();
        imgborde3 = new javax.swing.JLabel();
        TxtUsernamePassword = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        imgborde5 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        imgborde4 = new javax.swing.JLabel();
        jPanelENTRAR = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Txtuniversidad.setBackground(new java.awt.Color(255, 255, 255));
        Txtuniversidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelbarrasuperior.setBackground(new java.awt.Color(204, 204, 204));
        jPanelbarrasuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelbarrasuperiorMouseDragged(evt);
            }
        });
        jPanelbarrasuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelbarrasuperiorMousePressed(evt);
            }
        });

        jPanelsalida.setBackground(new java.awt.Color(204, 204, 204));

        TxtXsalida.setBackground(new java.awt.Color(153, 153, 153));
        TxtXsalida.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtXsalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtXsalida.setText("x");
        TxtXsalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtXsalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtXsalidaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelsalidaLayout = new javax.swing.GroupLayout(jPanelsalida);
        jPanelsalida.setLayout(jPanelsalidaLayout);
        jPanelsalidaLayout.setHorizontalGroup(
            jPanelsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsalidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TxtXsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelsalidaLayout.setVerticalGroup(
            jPanelsalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtXsalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelbarrasuperiorLayout = new javax.swing.GroupLayout(jPanelbarrasuperior);
        jPanelbarrasuperior.setLayout(jPanelbarrasuperiorLayout);
        jPanelbarrasuperiorLayout.setHorizontalGroup(
            jPanelbarrasuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbarrasuperiorLayout.createSequentialGroup()
                .addGap(0, 934, Short.MAX_VALUE)
                .addComponent(jPanelsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelbarrasuperiorLayout.setVerticalGroup(
            jPanelbarrasuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbarrasuperiorLayout.createSequentialGroup()
                .addComponent(jPanelsalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Txtuniversidad.add(jPanelbarrasuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 20));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("teniendo problemas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 230, 60));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("para conectarte!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 230, 60));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¡Parece que estamos\n");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 230, 60));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 317, 233));

        jPanel2.setBackground(new java.awt.Color(123, 123, 123));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REINTENTAR");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 395, -1));

        Txtuniversidad.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 400, 270));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        Txtuniversidad.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, 280));

        TxtSergio.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxtSergio.setForeground(new java.awt.Color(0, 51, 102));
        TxtSergio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtSergio.setText("SERGIO ARBOLEDA");
        Txtuniversidad.add(TxtSergio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 280, 40));

        TxtUniver.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxtUniver.setForeground(new java.awt.Color(0, 51, 102));
        TxtUniver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtUniver.setText("UNIVERSIDAD");
        Txtuniversidad.add(TxtUniver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 280, 40));
        Txtuniversidad.add(ImgWifu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 280, 280));

        ImgCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city.png"))); // NOI18N
        Txtuniversidad.add(ImgCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 280, 490));

        TxtUniversidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TxtUniversidad.setForeground(new java.awt.Color(0, 102, 153));
        TxtUniversidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Txtuniversidad.add(TxtUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 280, 62));
        Txtuniversidad.add(ImgMinticl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 40));

        TxtINVENTARO.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxtINVENTARO.setText("INVENTARIO CAFETERIA ");
        Txtuniversidad.add(TxtINVENTARO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 290, 40));

        TxtSQLserver.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TxtSQLserver.setText("SQL SERVER");
        Txtuniversidad.add(TxtSQLserver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, 40));

        TxtHostnamePort.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtHostnamePort.setText("Hostname/Port");
        Txtuniversidad.add(TxtHostnamePort, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 180, 140, 40));

        FieldHostname.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldHostname.setForeground(new java.awt.Color(204, 204, 204));
        FieldHostname.setText("Hostname");
        FieldHostname.setBorder(null);
        FieldHostname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldHostnameMousePressed(evt);
            }
        });
        FieldHostname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldHostnameActionPerformed(evt);
            }
        });
        Txtuniversidad.add(FieldHostname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 188, 200, -1));
        Txtuniversidad.add(imgborde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 183, 220, 30));

        FieldPort.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldPort.setForeground(new java.awt.Color(204, 204, 204));
        FieldPort.setText("Port");
        FieldPort.setBorder(null);
        FieldPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldPortMousePressed(evt);
            }
        });
        FieldPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPortActionPerformed(evt);
            }
        });
        Txtuniversidad.add(FieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 188, 130, -1));
        Txtuniversidad.add(imgborde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 183, 140, 30));

        TxtDatabase.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtDatabase.setText("Database");
        Txtuniversidad.add(TxtDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 250, 140, 40));

        FieldDatabase.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldDatabase.setForeground(new java.awt.Color(204, 204, 204));
        FieldDatabase.setText("Database");
        FieldDatabase.setBorder(null);
        FieldDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldDatabaseMousePressed(evt);
            }
        });
        FieldDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDatabaseActionPerformed(evt);
            }
        });
        Txtuniversidad.add(FieldDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 260, 140, -1));
        Txtuniversidad.add(imgborde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 257, 160, 30));

        TxtUsernamePassword.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        TxtUsernamePassword.setText("Username/Password ");
        Txtuniversidad.add(TxtUsernamePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 40));

        FieldUsername.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldUsername.setForeground(new java.awt.Color(204, 204, 204));
        FieldUsername.setText("Username");
        FieldUsername.setBorder(null);
        FieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FieldUsernameMousePressed(evt);
            }
        });
        FieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsernameActionPerformed(evt);
            }
        });
        Txtuniversidad.add(FieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 160, -1));
        Txtuniversidad.add(imgborde5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 326, 180, 30));

        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("**********");
        PasswordField.setBorder(null);
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        Txtuniversidad.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 332, 120, -1));
        Txtuniversidad.add(imgborde4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 326, 140, 30));

        jPanelENTRAR.setBackground(new java.awt.Color(0, 134, 190));
        jPanelENTRAR.setForeground(new java.awt.Color(0, 134, 190));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelENTRARLayout = new javax.swing.GroupLayout(jPanelENTRAR);
        jPanelENTRAR.setLayout(jPanelENTRARLayout);
        jPanelENTRARLayout.setHorizontalGroup(
            jPanelENTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanelENTRARLayout.setVerticalGroup(
            jPanelENTRARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Txtuniversidad.add(jPanelENTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Txtuniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Txtuniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldHostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldHostnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldHostnameActionPerformed

    private void FieldPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPortActionPerformed

    private void FieldDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDatabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDatabaseActionPerformed

    private void FieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsernameActionPerformed

    private void jPanelbarrasuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarrasuperiorMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanelbarrasuperiorMousePressed

    private void jPanelbarrasuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelbarrasuperiorMouseDragged
        int x = evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanelbarrasuperiorMouseDragged

    private void TxtXsalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_TxtXsalidaMouseClicked

    private void TxtXsalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseEntered
        jPanelsalida.setBackground(Color.red);
        TxtXsalida.setForeground(Color.white);
    }//GEN-LAST:event_TxtXsalidaMouseEntered

    private void TxtXsalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtXsalidaMouseExited
        jPanelsalida.setBackground(new Color(204, 204, 204));
        TxtXsalida.setForeground(Color.black);
    }//GEN-LAST:event_TxtXsalidaMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        if(jPanel1.isVisible() == false){
            jPanelENTRAR.setBackground(new Color(0,156,223));
        }
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        if(jPanel1.isVisible() == false){
        jPanelENTRAR.setBackground(new Color(0,134,190));
        }
    }//GEN-LAST:event_jLabel1MouseExited

    private void FieldHostnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldHostnameMousePressed
        if(FieldHostname.getText().equals("Hostname")){
            FieldHostname.setText("");
            FieldHostname.setForeground(Color.black);
        }
        if(String.valueOf(PasswordField.getPassword()).isEmpty()){
            PasswordField.setText("**********");
            PasswordField.setForeground(Color.gray);
        }
        if(FieldPort.getText().isEmpty()){
            FieldPort.setText("Port");
            FieldPort.setForeground(Color.gray);
        }
        if(FieldDatabase.getText().isEmpty()){
            FieldDatabase.setText("Database");
            FieldDatabase.setForeground(Color.gray);
        }
        if(FieldUsername.getText().isEmpty()){
            FieldUsername.setText("Username");
            FieldUsername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldHostnameMousePressed

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        if(String.valueOf(PasswordField.getPassword()).equals("**********")){
            PasswordField.setText("");
            PasswordField.setForeground(Color.black);
        }
        if(FieldPort.getText().isEmpty()){
            FieldPort.setText("Port");
            FieldPort.setForeground(Color.gray);
        }
        if(FieldDatabase.getText().isEmpty()){
            FieldDatabase.setText("Database");
            FieldDatabase.setForeground(Color.gray);
        }
        if(FieldUsername.getText().isEmpty()){
            FieldUsername.setText("Username");
            FieldUsername.setForeground(Color.gray);
        }
        if(FieldHostname.getText().isEmpty()){
            FieldHostname.setText("Hostname");
            FieldHostname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void FieldPortMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldPortMousePressed
        if(FieldPort.getText().equals("Port")){
            FieldPort.setText("");
            FieldPort.setForeground(Color.black);
        }
        if(String.valueOf(PasswordField.getPassword()).isEmpty()){
            PasswordField.setText("**********");
            PasswordField.setForeground(Color.gray);
        }
        if(FieldHostname.getText().isEmpty()){
            FieldHostname.setText("Hostname");
            FieldHostname.setForeground(Color.gray);
        }
        if(FieldDatabase.getText().isEmpty()){
            FieldDatabase.setText("Database");
            FieldDatabase.setForeground(Color.gray);
        }
        if(FieldUsername.getText().isEmpty()){
            FieldUsername.setText("Username");
            FieldUsername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldPortMousePressed

    private void FieldDatabaseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldDatabaseMousePressed
        if(FieldDatabase.getText().equals("Database")){
            FieldDatabase.setText("");
            FieldDatabase.setForeground(Color.black);
        }
        if(String.valueOf(PasswordField.getPassword()).isEmpty()){
            PasswordField.setText("**********");
            PasswordField.setForeground(Color.gray);
        }
        if(FieldHostname.getText().isEmpty()){
            FieldHostname.setText("Hostname");
            FieldHostname.setForeground(Color.gray);
        }
        if(FieldPort.getText().isEmpty()){
            FieldPort.setText("Port");
            FieldPort.setForeground(Color.gray);
        }
        if(FieldUsername.getText().isEmpty()){
            FieldUsername.setText("Username");
            FieldUsername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldDatabaseMousePressed

    private void FieldUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldUsernameMousePressed
        if(FieldUsername.getText().equals("Username")){
            FieldUsername.setText("");
            FieldUsername.setForeground(Color.black);
        }
        if(String.valueOf(PasswordField.getPassword()).isEmpty()){
            PasswordField.setText("**********");
            PasswordField.setForeground(Color.gray);
        }
        if(FieldHostname.getText().isEmpty()){
            FieldHostname.setText("Hostname");
            FieldHostname.setForeground(Color.gray);
        }
        if(FieldDatabase.getText().isEmpty()){
            FieldDatabase.setText("Database");
            FieldDatabase.setForeground(Color.gray);
        }
        if(FieldPort.getText().isEmpty()){
            FieldPort.setText("Port");
            FieldPort.setForeground(Color.gray);
        }
    }//GEN-LAST:event_FieldUsernameMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HOSTNAME = FieldHostname.getText();
        PORT = FieldPort.getText();
        DATABASE = FieldDatabase.getText();
        USERNAME = FieldUsername.getText();
        PASSWORD = PasswordField.getText();
        if(Conectar()==true){
            Alimentos AL = new Alimentos();
            AL.setVisible(true);
            AL.setLocationRelativeTo(null);
            this.setVisible(false);
        }else if(Conectar()==false){
            jPanel4.setVisible(true);
            jPanel1.setVisible(true);
            SetImageLabel(jLabel2,"src/imagenes/pr2.png");
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jPanel2.setBackground(new Color(110, 110, 110));
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jPanel2.setBackground(new Color(123, 123, 123));
        jLabel6.setForeground(Color.black);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        jPanel1.setVisible(false);
        jPanel4.setVisible(false);
        jPanelENTRAR.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_jLabel6MousePressed
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connexion().setVisible(true);
            }
        });
    }
    private void SetImageLabel(JLabel labelName,String root){
        ImageIcon image=new ImageIcon(root);
        Icon icon=new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(),labelName.getHeight(),Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    public Boolean Conectar(){
    try{
        con = DriverManager.getConnection("jdbc:mysql://"+HOSTNAME+":"+PORT+"/"+DATABASE+"?useSSL=false"
                ,USERNAME,PASSWORD);
        return true;
    } catch(SQLException e){
        return false;
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldDatabase;
    private javax.swing.JTextField FieldHostname;
    private javax.swing.JTextField FieldPort;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JLabel ImgCity;
    private javax.swing.JLabel ImgMinticl;
    private javax.swing.JLabel ImgWifu;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel TxtDatabase;
    private javax.swing.JLabel TxtHostnamePort;
    private javax.swing.JLabel TxtINVENTARO;
    private javax.swing.JLabel TxtSQLserver;
    private javax.swing.JLabel TxtSergio;
    private javax.swing.JLabel TxtUniver;
    private javax.swing.JLabel TxtUniversidad;
    private javax.swing.JLabel TxtUsernamePassword;
    private javax.swing.JLabel TxtXsalida;
    private javax.swing.JPanel Txtuniversidad;
    private javax.swing.JLabel imgborde1;
    private javax.swing.JLabel imgborde2;
    private javax.swing.JLabel imgborde3;
    private javax.swing.JLabel imgborde4;
    private javax.swing.JLabel imgborde5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelENTRAR;
    private javax.swing.JPanel jPanelbarrasuperior;
    private javax.swing.JPanel jPanelsalida;
    // End of variables declaration//GEN-END:variables
}
