/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hogud
 */
public class TablaSet extends javax.swing.JFrame {
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    static String DTabla;
    static String FTabla;
    static String FClave;
    static String FNombre;
    static String FPrecio;
    static String FInventario;
    static Boolean MTable;
    public TablaSet() {
        initComponents();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelINVENTARIO = new javax.swing.JPanel();
        TxtINVENTARO = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FieldUsername = new javax.swing.JTextField();
        imgborde5 = new javax.swing.JLabel();
        jPanelINVENTARIO1 = new javax.swing.JPanel();
        TxtINVENTARO3 = new javax.swing.JLabel();
        jPanelLIMPIAR1 = new javax.swing.JPanel();
        TxtLIMPIAR1 = new javax.swing.JLabel();
        jPanelLIMPIAR = new javax.swing.JPanel();
        TxtLIMPIAR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanelINVENTARIO.setBackground(new java.awt.Color(255, 255, 255));
        jPanelINVENTARIO.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TxtINVENTARO.setBackground(new java.awt.Color(255, 255, 255));
        TxtINVENTARO.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        TxtINVENTARO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtINVENTARO.setText("INVENTARIO CAFETERIA ");

        javax.swing.GroupLayout jPanelINVENTARIOLayout = new javax.swing.GroupLayout(jPanelINVENTARIO);
        jPanelINVENTARIO.setLayout(jPanelINVENTARIOLayout);
        jPanelINVENTARIOLayout.setHorizontalGroup(
            jPanelINVENTARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINVENTARIOLayout.createSequentialGroup()
                .addComponent(TxtINVENTARO, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelINVENTARIOLayout.setVerticalGroup(
            jPanelINVENTARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtINVENTARO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FieldUsername.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        FieldUsername.setForeground(new java.awt.Color(204, 204, 204));
        FieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FieldUsername.setText("Nueva tabla");
        FieldUsername.setBorder(null);
        FieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FieldUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FieldUsernameMouseExited(evt);
            }
        });
        FieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(FieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 152, 180, 30));

        imgborde5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(imgborde5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 200, 30));

        jPanelINVENTARIO1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelINVENTARIO1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TxtINVENTARO3.setBackground(new java.awt.Color(255, 255, 255));
        TxtINVENTARO3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TxtINVENTARO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtINVENTARO3.setText("TABLA A CONSULTAR");

        javax.swing.GroupLayout jPanelINVENTARIO1Layout = new javax.swing.GroupLayout(jPanelINVENTARIO1);
        jPanelINVENTARIO1.setLayout(jPanelINVENTARIO1Layout);
        jPanelINVENTARIO1Layout.setHorizontalGroup(
            jPanelINVENTARIO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINVENTARIO1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtINVENTARO3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelINVENTARIO1Layout.setVerticalGroup(
            jPanelINVENTARIO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelINVENTARIO1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtINVENTARO3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelINVENTARIO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 270, 50));

        jPanelLIMPIAR1.setBackground(new java.awt.Color(207, 207, 207));

        TxtLIMPIAR1.setBackground(new java.awt.Color(180, 180, 180));
        TxtLIMPIAR1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtLIMPIAR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtLIMPIAR1.setText("CANCELAR");
        TxtLIMPIAR1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtLIMPIAR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtLIMPIAR1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtLIMPIAR1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtLIMPIAR1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelLIMPIAR1Layout = new javax.swing.GroupLayout(jPanelLIMPIAR1);
        jPanelLIMPIAR1.setLayout(jPanelLIMPIAR1Layout);
        jPanelLIMPIAR1Layout.setHorizontalGroup(
            jPanelLIMPIAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelLIMPIAR1Layout.setVerticalGroup(
            jPanelLIMPIAR1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelLIMPIAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jPanelLIMPIAR.setBackground(new java.awt.Color(207, 207, 207));

        TxtLIMPIAR.setBackground(new java.awt.Color(180, 180, 180));
        TxtLIMPIAR.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        TxtLIMPIAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtLIMPIAR.setText("ACEPTAR");
        TxtLIMPIAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtLIMPIAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtLIMPIARMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelLIMPIARLayout = new javax.swing.GroupLayout(jPanelLIMPIAR);
        jPanelLIMPIAR.setLayout(jPanelLIMPIARLayout);
        jPanelLIMPIARLayout.setHorizontalGroup(
            jPanelLIMPIARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanelLIMPIARLayout.setVerticalGroup(
            jPanelLIMPIARLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtLIMPIAR, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelLIMPIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/26.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldUsernameActionPerformed

    private void TxtLIMPIARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseClicked
        DTabla=FieldUsername.getText();
        if(tablaSet(DTabla)==true){
            MTable=true;
            Alimentos AL = new Alimentos();
            AL.setVisible(true);
            AL.setLocationRelativeTo(null);
            this.setVisible(false);
        }else if (tablaSet(DTabla)==false){
            FieldUsername.setText("Tabla no valida");
            FieldUsername.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_TxtLIMPIARMouseClicked

    private void TxtLIMPIARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseEntered
        jPanelLIMPIAR.setBackground(new Color(170,194,215));
    }//GEN-LAST:event_TxtLIMPIARMouseEntered

    private void TxtLIMPIARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIARMouseExited
        jPanelLIMPIAR.setBackground(new Color(207,207,207));
    }//GEN-LAST:event_TxtLIMPIARMouseExited

    private void TxtLIMPIAR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIAR1MouseClicked
        try{
            Alimentos AL = new Alimentos();
            AL.setVisible(true);
            AL.setLocationRelativeTo(null);
            this.setVisible(false);
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_TxtLIMPIAR1MouseClicked

    private void TxtLIMPIAR1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIAR1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLIMPIAR1MouseEntered

    private void TxtLIMPIAR1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtLIMPIAR1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLIMPIAR1MouseExited

    private void FieldUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldUsernameMouseEntered
        if(FieldUsername.getText().equals("Nueva tabla") || FieldUsername.getText().equals("Tabla no valida")){
            FieldUsername.setText("");
            FieldUsername.setForeground(Color.black);
        }
    }//GEN-LAST:event_FieldUsernameMouseEntered

    private void FieldUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FieldUsernameMouseExited
        if(FieldUsername.getText().equals("") || FieldUsername.getText().equals("Tabla no valida")){
            FieldUsername.setText("Nueva tabla");
            FieldUsername.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_FieldUsernameMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaSet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaSet().setVisible(true);
            }
        });
    }
    public Boolean tablaSet(String DTabla){
        Object[] cosas = new Object[1];
        String f = "";
        int i=0;
        try {
            ps = con.prepareStatement("DESCRIBE "+DTabla+"");
            rs = ps.executeQuery();
            while(rs.next()){
                cosas[0] = rs.getString("Field");
                System.out.println(cosas[0].toString());
                if (i==0){
                    f= cosas[0].toString();
                }else{                  
                    f= f+" "+cosas[0].toString();
                }
                i++;
            }
            String[] x = f.split(" ");
            FTabla=DTabla;
            FClave=x[0];
            FNombre=x[1];
            FPrecio=x[2];
            FInventario=x[3];
            return true;
        } catch (SQLException ex) {
            return false;
        }
        }
    public void Conectar(){
        try{
        con = DriverManager.getConnection("jdbc:mysql://"+Connexion.HOSTNAME+":"+Connexion.PORT+"/"+Connexion.DATABASE+"?useSSL=false"
                ,Connexion.USERNAME,Connexion.PASSWORD);
        System.out.println("Conectado papa");
        } catch(SQLException e){
        //JOptionPane.showMessageDialog(null, e.toString());
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JLabel TxtINVENTARO;
    private javax.swing.JLabel TxtINVENTARO3;
    private javax.swing.JLabel TxtLIMPIAR;
    private javax.swing.JLabel TxtLIMPIAR1;
    private javax.swing.JLabel imgborde5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelINVENTARIO;
    private javax.swing.JPanel jPanelINVENTARIO1;
    private javax.swing.JPanel jPanelLIMPIAR;
    private javax.swing.JPanel jPanelLIMPIAR1;
    // End of variables declaration//GEN-END:variables
}
